### PR TITLE
Fix Abbey of Kings tooltip

### PR DESCRIPTION
**Pull request by LenaBullens**
As shown in the in game tech tree.

### CODE REVIEW

**Comment by robertvanhoesel** [comment]
Hi @LenaBullens,

Thanks for making this PR and spotting the mistake in the tooltip. I believe there may either be a bug in the code we use to generate the tooltips, or otherwise this would be best added [as a workaround](https://github.com/aoe4world/data/blob/main/src/attrib/workarounds.ts). The json files are rebuild/generated each time, so editing them directly is not advised. 

If you feel like it you can go through all the steps listed in Readme to build and verify these files, otherwise I'm more than happy to take a look later this week and see if there's an underlying bug that needs fixing.

**Comment by LenaBullens** [comment]
Looking at the locale file it has this for the tooltip: "Heals all nearby out of combat units by %1% every %2.1% seconds." So it seems like the seconds value isn't correctly parsed / converted? I'll see if I can get the parser running locally.

**Comment by robertvanhoesel** [comment]
@LenaBullens that would be great, however since the last patch from 1 hour ago the current parsing logic does not work anymore. I'm looking at it now!

**Comment by LenaBullens** [comment]
Ah, that's a shame.

I'm pretty sure, but I'm not very familiar with typescript, that the regex in interpolateGameString in /data/tree/main/src/lib/utils/game.ts stumbles on %2.1% seconds.

**Comment by robertvanhoesel** [comment]
That could very well be, you could look for a fix in isolation here without needing the whole project https://www.typescriptlang.org/play?&q=391#code/GYVwdgxgLglg9mABDMUCmAnADnANgQ3QGUoMUBzACgGdSAuRWsscgGkQDd9cQ1qGmFANoBdAJSIA3gFgAUIk7de1RAF5EQgHTauPPiIDcchRjRQQGJE2MLEm01gIQ0lAPQBSSgB0AJgGoxd1c2REoAfXYAD3YUHzRIiVUAPkU9ak1qAAsYYChKCQB+AsQAIiKCkrEbBXs0R3xnN3cgkJL3Suq7BycXV28vPyEwDBEAv2D2Eq8wDvlbTVIYAFt8o1kAXzkt2QgEajw0TVw4KhR0bDxCNBJmKhKACTRuFW5cRDAnjAAjAE9EOBAUH+wEQuyWX0IiHAMCgKl+iHcAEZ3Ig0BxMH93AAmTTIxhoXZgHzpErsIQAcgAbOT2OTEeTxGIgA

**Comment by robertvanhoesel** [comment]
I'm merging this now, since I also updated the patch data manually while I fix the parsing. I moved the regex parsing error into #10

**Pull request merged**
